# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18woPLZOC_ZuQOLrgFSTu6cOfbm-MuflT
"""

# hello_github.py

def greet(name):
    """
    Function to greet the user by name.
    """
    return f"Hello, {name}! Welcome to GitHub."

# Main code
if __name__ == "__main__":
    user_name = input("Enter your name: ")
    message = greet(user_name)
    print(message)

